### ISSUE TITLE
Change the name of this package

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/RLInterface.jl#13]
The name of this package is not really appropriate. There is nothing specific to deep RL in it. It is more a reinforcement learning wrapper for POMDP/MDP model implemented with POMDPs.jl.

Here are some suggestions: 
`RLWrapper.jl`
`RLInterface.jl`
`POMDPRLWrapper.jl`

I think once we agreed on a name we should move this package to JuliaPOMDP and potentially add it to the registry.

**Comment by mykelk** [comment]
Sounds good.

**Comment by zsunberg** [comment]
yeah I agree

I don't have super strong feelings about the name; I think I like maybe POMDPEnvironments?

**OR** we could just put it in POMDPs.jl itself as a third interface level. My initial feeling is to keep a separate package though
