### ISSUE TITLE
Default type in calls to `convert_s`

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/RLInterface.jl#18]
The `step!` and `reset!` methods convert states to `Array{Float64, 1}`. 
Since this wrapper is mostly used in the context of deep RL, I suggest it converts to `Array{Float32, 1}` instead. 

Sometimes it could make sense to convert the states to multi-dimensional arrays instead, should the type passed to `convert_s` or `convert_o` be an option of the wrapper?

**Comment by zsunberg** [comment]
Yes! I think it should be an option (see my review)
