### ISSUE TITLE
Does this actually only work with discrete action spaces?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/RLInterface.jl#21]
The README says this only works with discrete action spaces, but I don't see why this has to be the case. What is preventing it from working with continuous ones?

**Comment by MaximeBouton** [comment]
The `step!` and `reset!` functions are agnostic to the nature of the action space. 

I think if the underlying problem supports continuous action it should be fine, this repo is just a wrapper after all. 

These functions need attention: `POMDPs.actions(env::Union{POMDPEnvironment, MDPEnvironment})`, `sample_action(env::Union{POMDPEnvironment, MDPEnvironment})`, `POMDPs.n_actions(env::Union{POMDPEnvironment, MDPEnvironment})`.
This might be more of a POMDPs.jl matter, I am not sure how could one specify a continuous action space, we have mostly worked with discrete action space problems and solvers.

**Comment by rejuvyesh** [comment]
The `ZMQServer` doesn't support continuous actions either. See https://github.com/JuliaPOMDP/RLInterface.jl/blob/master/src/ZMQServer.jl#L52

**Comment by zsunberg** [comment]
> I am not sure how could one specify a continuous action space

You would create a custom type representing the action space.

I just removed the note in a PR because I think it would work fine with the environments. There is currently no documentation about the ZMQ Server :man_facepalming: , so I didn't put a note that the server doesn't support continuous actions (it is probably easier to just use pyjulia at this point anyways).
