### ISSUE TITLE
RLInterface vs CommonRLInterface

### ISSUE THREAD

**Issue by johannes-fischer** [JuliaPOMDP/RLInterface.jl#36]
I'm wondering whether this package is still encouraged to be used, or if it has been replaced by [CommomRLInterface](https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl). 

What is the difference between the two? When would I use one over the other?

**Comment by zsunberg** [comment]
Yes, this is deprecated in favor of CommonRLInterface. If you see any links to this package, please file issues or PRs. I will make a note in the README now.

**Comment by johannes-fischer** [comment]
Thanks for the quick reply!
